
export interface Data {
    name: string,
    cargo_capacity: string,
    consumables: string,
    cost_in_credits: string,
    created: string,
    crew: string,
    edited: string,
    length: string,
    manufacturer: string,
    max_atmosphering_speed: string,
    model: string,
    passengers: string,
    pilots: string[],
    films: string[],
    url: string,
    hyperdrive_rating: string,
    MGLT: string,
    starship_class: string,
}